Creating a Node.js Application with Swagger and MySQL

SQL Database Create & Delete
    1. Open CMD Run as administrator
        create cmd : mysql -u root -p < "D:\Projects\R\studyforbuddy-backend\database\create.sql"
        delete cmd : mysql -u root -p < "D:\Projects\R\studyforbuddy-backend\database\delete.sql"